env:
    global:
        - REPO_DIR=uwsgi
        # Commit from your-project that you want to build
        - BUILD_COMMIT=2.0.19.1
        # pip dependencies to _build_ your project
        - BUILD_DEPENDS=""
        # pip dependencies to _test_ your project.  Include any dependencies
        # that you need, that are also specified in BUILD_DEPENDS, this will be
        # a separate install.
        - TEST_DEPENDS="pytest"
        # Use this to add a pre-release version to the end of the uWSGI version
        # e.g., a4, b1
        - APPEND_VERSION=".post0"
        - MB_ML_VER=2010
        # Exclude SSL from the wheel builds
        - UWSGI_PROFILE=pyuwsginossl
        - PLAT=x86_64
        - UNICODE_WIDTH=32

language: generic
services: docker
dist: xenial
# osx image that enables building Apple silicon libraries
osx_image: xcode12.2

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.9
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.7
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.8
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.9
        - PLAT="universal2"
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.9
before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - clean_code $REPO_DIR $BUILD_COMMIT
    - ./patch-uwsgi-packaging.sh $REPO_DIR
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

deploy:
  provider: s3
  access_key_id: "AKIAR7D27PGPLP6LMZM3"
  secret_access_key:
    secure: "FLdoK/S/FG5FnEevFJHOYykNRnEe8IUak2wgJTX2cSWptjBYM+jOcZcggZsgtDO7hJpZj6QqJGdLYdMz8CrAiVT0RnSDsJoYvUIMjzKYe9A7cyi4VvkcK23t42vMcw/eCvL/2L3qB9t9YqGWChoznyQ9pbyvcXB0wk0hj2kaEcPMeZDmbgV4HO6GAIi8pRo9BmQl6MqwOCG+KhYcjPjG+dIqZIbFd8GKgoHOXRkU+r2zr8gQiFB0n2G5kVbVgqAtWoH6kl5yxNZ02XJgF/aly1wTW0ogjOXGjp39+p4dAzGFbwXBRZTll2AjQ6wzCLSC8w4l/kTqmUCd2Kjfw6N+Qf5uUVXIqtCPNwraYxC3v8YYwwaDz+Dt5bGjAkXFcHK1CzrOx3/2L2Xlpln8oZZNzIxJ6YQBaZTicyzimJz8C4jJkYWsZpzPgSe01zc0Vyl5WfGFXx5xG2j/tK9zgZOdHTAeLg20xC6YNKE6zvhN3KjVp602uclcGjV4TslbC0xzp68aS/I7IaFDSj4yZ+bqmywjoVhp5sxNbUxQWPFM+kpvT6vApSca2jt4EJLLZeD2qHtZ3Lmh/+j5FOQk7Nras1ekG85FPb80vNjHmgwMhy5ILf+WaGxtl2JiBCfcRHDRywAc2830B3+g1jr4lBFXZPxu9VweyrzdgeS8u1LsUDE="
  bucket: "ll-share-public"
  skip_cleanup: true
  local_dir: wheelhouse
  upload-dir: pyuwsgi
