name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.9.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse uwsgi
        env:
          CIBW_SKIP: pp*
          CIBW_ENVIRONMENT: APPEND_VERSION=.post0 UWSGI_PROFILE=pyuwsginossl
          CIBW_TEST_COMMAND: pyuwsgi --help
          CIBW_BEFORE_ALL: ./patch-uwsgi-packaging.sh uwsgi
          # https://github.com/matthew-brett/delocate/pull/39
          CIBW_BEFORE_BUILD_MACOS: ./pre_build.sh && pip install https://github.com/natefoo/delocate/archive/06673679eaaf67db88cbe280456abbf988705d75.zip
          CIBW_BEFORE_BUILD_LINUX: ./pre_build.sh && yum install -y zlib-devel

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
